### ISSUE TITLE
Bug: El juego no termina al abrir todas las celdas

### ISSUE THREAD

**Issue by marioreinike** [vtespinosa/Proyecto-Testing#13]
Cuando se abren todas las celdas que no tienen minas, el juego no termina. Este problema sucede dentro del método `check_end_conditions` de la clase `Board`, cuando la última celda que se abre es del tipo 'Flag'.

También es necesario que el juego termine cuando todas las celdas que no contienen minas, sin tener que haberlas flaggeado.

**Comment by josem7** [comment]
Para ganar hay que descubir todas las celdas y ponerle flags a las minas!

**Comment by josem7** [comment]
fixed in 7a8ef47
